help_list = {
        '?': '[index]',
        '??': '[index]',
        'art': '(message)',
        'awakelb': '',
        'bigmoji': '(emojis)',
        'clean': '',
        'emojilist': '',
        'everyone': '',
        'help': '',
        'illegal': '(message)',
        'info': '[users]',
        'inspire': '',
        'letter': '(message)',
        'mcstatus': '(ip address:port)',
        'minesweeper': '[height] [length]',
        'ping': '[user]',
        'profanitylb': '',
        'quantum': '(message)',
        'ratespice': '[user]',
        'roll': '(number of times)',
        'stfu': '(user)',
        'user': '[user]',
        'wall': '(message)',
        'wiggle': '(message)',
}

admin_help_list = {
        'add': '{?, ??} (message)',
        'adminhelp': '',
        'changeprofanity': '[number=0] (user)',
}
